import { Platform, StyleSheet } from "react-native";
import theme from "../theme/Theme";

export const styles = StyleSheet.create({
    header: {
        position: "absolute",
        top: 0,
        left: 0,
        right: 0,
        height: 50,
        backgroundColor: theme.colors.background,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingHorizontal: 16,
        zIndex: 1000,
        elevation: 3,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 3,
        borderBottomWidth: 1,
        borderBottomColor: "#e0e0e0",
    },
    headerTitle: {
        fontSize: theme.fontSize.normal,
        fontWeight: "bold",
        color: theme.colors.secondary,
    },
    overlay: {
        position: "absolute",
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: "#00000066",
        zIndex: 998,
    },
    drawer: {
        position: "absolute",
        top: 0,
        left: 0,
        bottom: 0,
        backgroundColor: theme.colors.background,
        paddingTop: 70,
        paddingHorizontal: theme.spacing(2),
        zIndex: 999,
        elevation: 10,
        shadowColor: "#000",
        shadowOffset: { width: 4, height: 0 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
    },
    drawerTitle: {
        fontSize: theme.fontSize.large,
        fontWeight: "bold",
        marginBottom: theme.spacing(3),
        color: theme.colors.primary,
        paddingBottom: theme.spacing(2),
        borderBottomWidth: 1,
        borderBottomColor: "#e0e0e0",
    },
    itemsContainer: {
        flexDirection: "column",
        gap: 8,
        alignItems: "flex-start",
        width: "100%",
    },
    seccionLabel: {
        fontSize: 11,
        fontWeight: "bold",
        color: "#999",
        letterSpacing: 1,
        marginTop: theme.spacing(1),
        marginBottom: 4,
    },
    separador: {
        width: "100%",
        height: 1,
        backgroundColor: "#e0e0e0",
        marginVertical: theme.spacing(1),
    },
    drawerItem: {
        flexDirection: "row",
        alignItems: "center",
        paddingVertical: theme.spacing(1.5),
        paddingHorizontal: theme.spacing(1),
        width: "100%",
        borderRadius: 8,
    },
    drawerText: {
        marginLeft: 15,
        fontSize: theme.fontSize.normal,
        color: theme.colors.primary,
        fontWeight: "500",
    },
});